version: '{build}'
image: Visual Studio 2017
platform:
- x64
environment:
  pypipw:
    secure: KEEdTX/BJvkl9qQucfKEkQ==
  matrix:
  - PYTHON: 36
  - PYTHON: 37
install:
- ps: |
    git submodule update -q --init --recursive
    cmake --version
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      pip install --disable-pip-version-check --user --upgrade pip setuptools
      pip install wheel twine
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install -q conda-build
    }

test_script:
  - python setup.py test

after_test:
# - ps: |
#     if ($env:PYTHON) {
#       python setup.py sdist bdist_wheel upload
#       pip install --verbose dist\vectorialpsf-0.0.2-cp37-cp37m-win_amd64.whl
#     } else {
#       conda build conda.recipe
#       conda install --use-local vectorialpsf
#     }

build_script:
  - python setup.py sdist bdist_wheel

deploy_script:
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo repository: https://test.pypi.org/legacy/ >> %USERPROFILE%\\.pypirc"
  - "echo username: talley >> %USERPROFILE%\\.pypirc"
  - type "%USERPROFILE%\\.pypirc"
  - "echo password: %pypipw% >> %USERPROFILE%\\.pypirc"
  # - python setup.py bdist_wheel upload
  - twine upload dist\\*.whl