version: "{build}"
image: Visual Studio 2017
platform:
  - x64
environment:
  pypipw:
    secure: KEEdTX/BJvkl9qQucfKEkQ==
  matrix:
    - PYTHON: 35
    - PYTHON: 36
    - PYTHON: 37
install:
  - ps: |
      git submodule update -q --init --recursive
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      pip install --disable-pip-version-check --user --upgrade pip setuptools
      pip install wheel twine

test_script:
  - python setup.py test

build_script:
  - python setup.py bdist_wheel

deploy_script:
  - ps: |
      if (!$env:APPVEYOR_REPO_TAG) { 
        Exit-AppVeyorBuild
      }
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo repository: https://test.pypi.org/legacy/ >> %USERPROFILE%\\.pypirc"
  - "echo username: talley >> %USERPROFILE%\\.pypirc"
  - type "%USERPROFILE%\\.pypirc"
  - "echo password: %pypipw% >> %USERPROFILE%\\.pypirc"
  - twine --skip-existing upload dist\\*.whl
