version: '{build}'
image: Visual Studio 2017
platform:
- x64
environment:
  matrix:
  - PYTHON: 37
install:
- ps: |
    git submodule update -q --init --recursive
    cmake --version
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      pip install --disable-pip-version-check --user --upgrade pip setuptools wheel
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install -q conda-build
    }
build_script:
- ps: |
    if ($env:PYTHON) {
      python setup.py bdist_wheel
      pip install --verbose dist\vectorialpsf-0.0.2.tar.gz
    } else {
      conda build conda.recipe
      conda install --use-local vectorialpsf
    }
test_script:
- ps: python tests\test.py
